version: '3.2'
services:

    api-golang:
        image: golang
        volumes:
            - ./api:/var/www:delegated
        ports:
            - 8070:80
        working_dir: /var/www
        build:
            context: ./api/docker/golang
        command: go run ./main.go

    frontend-nodejs:
        image: node:13-alpine
        volumes:
            - ./frontend:/var/www/frontend:delegated
        working_dir: /var/www/frontend
        tty: true
        ports:
            - 8081:8080