version: '3.2'
services:

    api-golang:
        ports:
            - 8080:9081
        restart: unless-stopped
        build:
            context: ./
            dockerfile: ./docker/api/Dockerfile

    frontend-nodejs:
        image: node:13-alpine
        volumes:
            - ./frontend:/var/www/frontend:delegated
        working_dir: /var/www/frontend
        tty: true
        ports:
            - 8081:8080