version: '3.2'
services:

    api-golang:
        ports:
            - 8080:8080
        restart: unless-stopped
        build: ./api/docker

    frontend-nodejs:
        image: node:13-alpine
        volumes:
            - ./frontend:/var/www/frontend:delegated
        working_dir: /var/www/frontend
        tty: true
        ports:
            - 8081:8080